config/routes.rb
# frozen_string_literal: true


Webapp::Application.routes.draw do
  resources :assignments, only: [] do
    collection do
      get :knight
    end
  end

  resources :regions, except: [:show]

  resources :cell_carriers do as_routes end
  resources :transport_types do as_routes end

  resources :scale_types

  resources :absences do
    collection do
      get :all
    end
  end

  resources :logs do
    collection do
      get :by_day
      get :tardy
      get :last_ten
      get :open
      get :todo
      get :mine_past
      get :mine_upcoming
      get :being_covered
      get :new_absence
      get :create_absence
      get :receipt
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :stats_service
      get :stats
      get :export
    end
    member do
      get :take
      get :leave
    end
  end

  resources :schedule_chains do
    collection do
      get :today
      get :tomorrow
      get :yesterday
      get :open
      get :open_old
      get :mine
      get :mine_old
      get :take
      get :leave
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end
  end

  resources :locations do
    collection do
      get :recipients
      get :hubs
      get :sellers
      get :buyers
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end

    member do
      get :hud
    end
  end

  devise_for :volunteers, controllers: { sessions: 'sessions' }

  resources :volunteers do
    collection do
      get :home
      get :unassigned
      get :shiftless
      get :shiftless_old
      get :active
      get :inactive
      get :need_training
      get :super_admin
      get :region_admin
      get :stats
      get :shift_stats
      get :switch_user
      get :knight
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :assign
    end
    member do
      get :reactivate
    end
  end

  resource :waiver, only: [:new, :create]

  namespace :region_admin do
    resources :donors, only: [:index]

    resources :food_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :volunteer do
    authenticated do
      root to: 'volunteers#home'
    end

    unauthenticated do
      root to: 'sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/region.rb
# frozen_string_literal: true

class Region < ActiveRecord::Base
  has_many :assignments
  has_many :volunteers, through: :assignments
  has_many :food_types
  has_many :scale_types
  has_many :schedule_chains
  has_many :locations
  has_many :logs

  scope :all_admin, ->(volunteer) { where(id: volunteer.admin_region_ids) }

  geocoded_by :address, latitude: :lat, longitude: :lng # can also be an IP address
  after_validation :geocode

  attr_accessible :address, :lat, :lng, :name, :notes, :website, :handbook_url, :welcome_email_text,
                  :splash_html, :title, :tagline,
                  :phone, :tax_id, :twitter_key, :twitter_secret, :twitter_token,
                  :twitter_token_secret, :weight_unit, :time_zone, :logo, :post_pickup_emails,
                  :unschedule_self, :volunteer_coordinator_email

  has_attached_file :logo,
                    styles: { thumb: '50x50' },
                    s3_credentials: { bucket: 'boulder-food-rescue-robot-region-photo' }
  validates_attachment_file_name :logo, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]

  def self.any_handbooks?(region_list)
    region_list.any?(&:handbook?)
  end

  def active_volunteer_count
    schedule_chains.flat_map(&:volunteers).uniq.count
  end

  def sellers?
    locations.where(location_type: Location::LOCATION_TYPES.invert['Seller']).any?
  end

  def buyers?
    locations.where(location_type: Location::LOCATION_TYPES.invert['Buyer']).any?
  end

  def hubs?
    locations.where(location_type: Location::LOCATION_TYPES.invert['Hub']).any?
  end

  def handbook?
    handbook_url.present?
  end
end

app/controllers/logs_controller.rb
# frozen_string_literal: true

require 'prawn/table'

class LogsController < ApplicationController
  before_filter :authenticate_volunteer!, :except => :stats_service
  before_filter :admin_only, :only => [:today, :tomorrow, :yesterday, :being_covered, :tardy, :receipt, :new, :create, :stats, :export]

  def mine_past
    index(Log.past_for(current_volunteer.id), 'My Past Shifts')
  end

  def mine_upcoming
    index(Log.upcoming_for(current_volunteer.id), 'My Upcoming Shifts')
  end

  def open
    index(Log.needing_coverage(current_volunteer.region_ids), 'Open Shifts')
  end

  def by_day
    if params[:date].present?
      date = Date.civil(*params[:date].sort.map(&:last).map(&:to_i))
    else
      n = params[:n].present? ? params[:n].to_i : 0
      date = Time.zone.today + n
    end
    index(Log.where("region_id IN (#{current_volunteer.region_ids.join(',')}) AND \"when\" = '#{date}'"), "Shifts on #{date.strftime('%A, %B %-d')}")
  end

  def last_ten
    logs = Log.where(region_id: current_volunteer.region_ids)
              .where('"when" >= ?', Time.zone.today - 10)
    index(logs, 'Last 10 Days of Shifts')
  end

  def being_covered
    index(Log.being_covered(current_volunteer.region_ids), 'Being Covered')
  end

  def todo
    index(Log.past_for(current_volunteer.id).where('"when" < current_date AND NOT complete'), 'My To Do Shift Reports')
  end

  def tardy
    index(Log.where("region_id IN (#{current_volunteer.region_ids.join(',')}) AND \"when\" < current_date AND NOT complete and num_reminders >= 3", 'Missing Data (>= 3 Reminders)'), 'Missing Data (>= 3 Reminders)')
  end

  def index(logs=nil, header='Entire Log')
    @shifts = []
    unless current_volunteer.region_ids.empty?
      @shifts = Shift.build_shifts(logs.nil? ? Log.where(region_id: current_volunteer.region_ids) : logs)
    end

    respond_to do |format|
      format.json { render json: @shifts }
      format.html {
        @header = header
        @my_admin_regions = current_volunteer.admin_regions
        render :index
      }
    end
  end

  def stats
    @regions = current_volunteer.admin_regions
    region_ids = current_volunteer.admin_region_ids

    @first_recorded_pickup = Log.where(region_id: region_ids)
                                .complete
                                .order('logs.when ASC')
                                .limit(1)
    @pounds_per_year = Log.joins(:log_parts)
                          .select('extract(YEAR from logs.when) as year, sum(weight)')
                          .where(region_id: region_ids)
                          .complete
                          .group('year')
                          .order('year ASC')
                          .collect{ |l| [l.year, l.sum] }
    @pounds_per_month = Log.joins(:log_parts)
                           .select("date_trunc('month',logs.when) as month, sum(weight)")
                           .where(region_id: region_ids)
                           .complete
                           .group('month')
                           .order('month ASC')
                           .collect{ |log| [Date.parse(log.month).strftime('%Y-%m'), log.sum] }
    @transport_per_year = {}
    @transport_years = []
    @transport_data = Log.joins(:transport_type)
                         .select('extract(YEAR from logs.when) as year, transport_types.name, count(*)')
                         .where(region_id: region_ids)
                         .complete
                         .group('name, year')
                         .order('name, year ASC')
    @transport_data.each do |log|
      @transport_years << log.year unless @transport_years.include?(log.year)
      @transport_per_year[log.name] = [] if @transport_per_year[log.name].nil?
    end
    @transport_per_year.each_key do |key|
      @transport_per_year[key] = @transport_years.collect{ |_y| 0 }
    end
    @transport_data.each do |log|
      @transport_per_year[log.name][@transport_years.index(log.year)] = log.count.to_i
    end
  end

  def stats_service
    case params[:what]
    when 'poundage'
      if params[:region_id].nil?
        total = LogPart.sum(:weight) + Region.where('prior_lbs_rescued IS NOT NULL').sum('prior_lbs_rescued')
      else
        region_id = params[:region_id]
        @region = Region.find(region_id)
        total = Log.joins(:log_parts).where('region_id = ? AND complete', region_id).sum('weight').to_f
        total += @region.prior_lbs_rescued.to_f unless @region.nil? or @region.prior_lbs_rescued.nil?
      end
      render text: total.to_s
    when 'wordcloud'
      words = {}
      LogPart.select('description').where('description IS NOT NULL').each{ |log_part|
        log_part.description.strip.split(/\s*\,\s*/).each{ |word|
          word = word.strip.downcase.tr(',', '')
          next if word =~ /(nothing|no |none)/ or word =~ /etc/ or word =~ /n\/a/ or word =~ /misc/
          # people cannot seem to spell the most delicious fruit correctly
          word = 'avocados' if %w(avacados avocadoes avocado).include?(word)
          words[word] = 0 if words[word].nil?
          words[word] += 1
        }
      }
      render :text => words.collect{ |k, v| (v >= 10) ? "#{k}:#{v}" : nil }.compact.join(',')
    when 'transport'
      rq = ''
      wq = ''
      rq = "AND region_id=#{params[:region_id].to_i}" if params[:region_id]
      wq = "AND \"when\" > NOW() - interval '1 month'" if params[:timespan] == 'month'
      noncar = Log.where("complete AND transport_type_id IN (SELECT id FROM transport_types WHERE name != 'Car') #{rq} #{wq}").count.to_f
      car = Log.where("complete AND transport_type_id IN (SELECT id FROM transport_types WHERE name = 'Car') #{rq} #{wq}").count.to_f
      render :text => "#{100.0*noncar/(noncar+car)} #{100.0*car/(noncar+car)}"
    else
      render :text => 'NO'
    end
  end

  def destroy
    @log = Log.find(params[:id])
    authorize! :destroy, @log
    @log.destroy
    redirect_to(request.referrer)
  end

  def new
    @region = Region.find(params[:region_id])
    @log = Log.new(region_id: @region.id)
    @action = 'create'
    authorize! :create, @log
    session[:my_return_to] = request.referer
    set_vars_for_form @region
  end

  def create
    @log = Log.new(params[:log])
    @region = @log.region
    @food_types = @region.food_types.collect{ |e| [e.name, e.id] }
    @scale_types = @region.scale_types.collect{ |e| [e.name, e.id] }
    @transport_types = TransportType.all.collect{ |e| [e.name, e.id] }

    if @scale_types.empty?
      flash[:error] = "You have no scale types for the 'Weighed With' field for #{@region.name}. Please get this set up for your region."
      render :new and return
    end

    @log.scale_type_id ||= @region.scale_types.first.id if @scale_types.any?

    authorize! :create, @log
    parse_and_create_log_parts(params, @log)
    finalize_log(@log)

    if @log.save
      flash[:notice] = 'Created successfully.'
      return session[:my_return_to].present? ? redirect_to(session[:my_return_to]) : index
    else
      flash[:error] = "Didn't save successfully :(. #{@log.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def show
    @log = Log.find(params[:id])
    authorize! :read, @log
    respond_to do |format|
      format.html
      format.json {
        attrs = {}
        attrs[:log] = @log.attributes
        attrs[:log][:recipient_ids] = @log.recipient_ids
        attrs[:log][:volunteer_ids] = @log.volunteer_ids
        attrs[:log][:volunteer_names] = @log.volunteers.collect{ |v| v.name }
        attrs[:schedule] = @log.schedule_chain.attributes unless @log.schedule_chain.nil?
        attrs[:log_parts] = {}
        @log.log_parts.each{ |lp| attrs[:log_parts][lp.id] = lp.attributes }
        render json: attrs
      }
    end
  end

  def edit
    @log = Log.find(params[:id])
    authorize! :update, @log
    @region = @log.region
    @action = 'update'
    session[:my_return_to] = request.referer
    set_vars_for_form @region
    render :edit
  end

  def update
    @log = Log.find(params[:id])
    @region = @log.region
    @action = 'update'
    set_vars_for_form @region

    unless can?(:update, @log)
      flash[:notice] = 'Not authorized to edit that log item.'
      respond_to do |format|
        format.json { render json: {:error => 1, :message => flash[:notice] } }
        format.html { redirect_to(root_path) }
      end
      return
    end

    parse_and_create_log_parts(params, @log)

    if @log.update_attributes(params[:log])
      finalize_log(@log)

      if @log.save
        if @log.complete
          flash[:notice] = 'Updated Successfully. All done!'
        else
          flash[:warning] = "Saved, but some weights/counts still needed to complete this log. Finish it here: <a href=\"/logs/#{@log.id}/edit\">(Fill In)</a>".html_safe
        end
        respond_to do |format|
          format.json { render json: { error: 0, message: flash[:notice] } }
          format.html { render :edit }
        end
      else
        flash[:error] = 'Failed to mark as complete.'
        respond_to do |format|
          format.json { render json: { error: 2, message: flash[:notice] } }
          format.html { render :edit }
        end
      end
    else
      flash[:error] = "Didn't update successfully :(. #{@log.errors.full_messages.to_sentence}"
      respond_to do |format|
        format.json { render json: { error: 1, message: flash[:notice] } }
        format.html { render :edit }
      end
    end
  end

  # can be given a single id or a list of ids
  def take
    logs = params[:ids].present? ? Log.find(params[:ids]) : [Log.find(params[:id])]

    if logs.all? { |log| can?(:take, log) }
      logs.each { |log| LogVolunteer.create(volunteer: current_volunteer, covering: true, log: log) }
      flash[:notice] = "Successfully took a shift with #{logs.length} donor(s)."
    else
      flash[:notice] = "Cannot take shifts for regions that you aren't assigned to!"
    end

    respond_to do |format|

app/views/logs/_form.html.erb
<%= simple_form_for @log, url: {action: @action}, class: 'form-horizontal' do |f| %>
  <!-- Errors -->
  <% if @log.errors.any? %>
    <div class="row">
      <div id="error_explanation">
        <strong><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</strong>
        <ul>
          <% @log.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= hidden_field_tag "log[region_id]", @region.id %>
      <%= hidden_field_tag "log[schedule_chain_id]", @log.schedule_chain.nil? ? nil : @log.schedule_chain.id  %>
      <details>
        Date of Food Rescue
        <div class="form-inline">
          <%= f.date_select :when, {order: [:month, :day, :year]}, {class: 'form-control'} %>
        </div>
        <h5>Name of Volunteers</h5>
        <div>
          <%= f.simple_fields_for :log_volunteers do |log_volunteer| %>
            <%= render 'log_volunteer_fields', :f => log_volunteer %>
          <% end %>
          <br/>
          <%= link_to_add_association 'add another volunteer', f, :log_volunteers, class: 'btn btn-primary' %>
        </div>
        <% if current_volunteer.any_admin?(@log.region) %>
          Needed Volunteers<br/>
          <span class="subtext">Default is the number required by the associated schedule, or at least one.</span>
          <%= f.text_field(:num_volunteers, class: "form-control") %>
        <% end %>
        <h5>Where are you picking up from?</h5>
        <%= f.select :donor_id, (@locations).collect {|d| [d.name, d.id]}, {include_blank: false}, {class: 'form-control select2'} %>

        <h5>What is the drop off location?</h5>
        <div>
          <%= f.simple_fields_for :log_recipients do |log_recipient| %>
            <%= render 'log_recipient_fields', :f => log_recipient %>
          <% end %>
          <%= link_to_add_association 'add another recipient', f, :log_recipients, :class => 'btn' %>
        </div>
          </details>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="mb-3">
        <label for="username">How did you transport this food?</label>
        <div class="input-group" style="width: 50%;">
          <%= f.select(:transport_type_id, @transport_types, {:include_blank => true}, {class: "form-control"}) %>
        </div>
      </div>
      <br>
      <div class="mb-3">
        <% @log_parts.each_with_index {|lp, index| %>
          <%= fields_for :log_parts, lp, :index => "update_#{index}" do |f2| %>
            <tr class="log_part" style="background: <%= lp.required ? "lightgrey" : "white" %>;">
              <td>
                <%= f2.label_tag(:weight, 'Weight of food (lbs.):') %>
                <%= f2.number_field(:weight, size: 5, class: "form-control", min: 0) %>
              </td>
              <br>
              <td>
                <%= label_tag(:description, "Summary of food types:") %>
                <%= f2.text_area(:description, size: "20x2", class: "form-control") %>
                <%= f2.hidden_field(:id) %>
                <%= f2.hidden_field(:food_type_id) %>
              </td>
              <br>
              <td>
                <%= f2.label_tag(:compost_weight, 'Weight of Compost (lbs.):') %>
                <%= f2.number_field(:compost_weight, size: 5, class: "form-control", min: 0) %>
              </td>
              <br>
            </tr>
          <% end %>
        <% } %>

          </tr>
      </div>
      <br>
      <div class="mb-3">
        <label for=:hours_spent>Length of shift (in hours):</label>
        <%= f.number_field(:hours_spent, :size => "3", class: "form-control", min: 0) %>
      </div>
      <br>
      <div class="mb-3">
        <label for=:notes>Any comments, concerns, notes?
        </label>
        <%= f.text_area(:notes, :size => "30x6", class: "form-control") %>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-12">
          <td>
            Flag For Admin<br/>
            <span class="subtext">Check this if you want to make sure someone reads this.</span>
          </td>
          <td>
            <div class="checkbox">
              <label for="log_flag_for_admin">
                <%= f.check_box(:flag_for_admin) %>
                Flag
              </label>
            </div>
          </td>
          </tr>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <%= submit_tag %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% content_for :scripts do %>
  <script type="text/javascript" charset="utf-8">
      function update_total_weight(){
          t = 0.0
          $( "input[id$='weight']").each(function(i){
              v = $(this).val()
              if(v != "" && v != undefined) {
                  t = t + parseFloat(v)
              }
          })
          if(isNaN(t) || t <= 0){
              $("#zero_reason").show();
          }else{
              $("#zero_reason").hide();
          }
          $("#total_weight").text(t)
      }

      jQuery(document).ready(function() {

          update_total_weight();
          $( "input[id$='weight']").each(function(i){
              $(self).on("change",function(){
                  update_total_weight();
              });
          });
      });
  </script>
<% end %>

app/views/logs/_log_part_fields.html.erb
<div class="nested-fields">
    <tr class="log_part">
      <td>
        <%= f.label_tag(:location_admin_id, 'Select Vendor:') %>
        <%= f.select(:location_admin_id,  @vendors.collect{|p| [p.name, p.id]}, {:include_blank => false}, {class: "form-control select-vendor"}) %>
      </td>
      <br>
      <td>
        <%= f.label_tag(:weight, 'Weight of Food(lbs.):') %>
        <%= f.number_field(:weight, size: 5, class: "form-control food-weight", min: 0) %>
      </td>
      <br>
      <td>
        <%= label_tag(:description, "Summary of food types:") %>
        <%= f.text_area(:description, size: "20x2", class: "form-control") %>
        <%= f.hidden_field(:id) %>

        <%= f.hidden_field(:food_type_id, value:1) %>
      </td>
      <td> <%= link_to_remove_association "Remove", f , class: 'btn btn-danger change-num-vendors'%></td>
      <br>
      <td>
        <%= f.hidden_field(:compost_weight, min: 0) %>
      </td>
      <br>
    </tr>

</div>

app/views/logs/_log_recipient_fields.html.erb
<div class="nested_fields">
  <%= f.association :recipient, :collection => (@region.locations.recipients + @region.locations.hubs + @region.locations.buyers), :as=>:select, :label=>false, :input_html => {:class => 'form-control select2', :tabindex => '-1'} %>
</div>

app/views/logs/_log_volunteer_fields.html.erb
<div class="nested_fields">
  <%= f.association :volunteer, :collection => @region.volunteers, :as => :select, :label => false, :input_html => {:class => 'form-control select2', :tabindex => '-1'} %>
</div>

app/views/logs/_take_or_leave.html.erb
<% volunteers = logs.collect{ |log| log.volunteers }.flatten.uniq %>
<% if volunteers.include?(current_volunteer) %>
  <% if volunteers.length > 1 %>
    <%= link_to "(Leave it)", controller: "logs", action: "leave", id: logs[0], ids: logs.collect{ |log| log.id } %>
  <% end %>
<% else %>
  <%= link_to "(Join it)", controller: "logs", action: "take", id: logs, ids: logs.collect{ |log| log.id } %>
<% end %>

app/views/logs/edit.html.erb
<h2>Edit Pick-up Report</h2>
<%= render partial: "form" %>

app/views/logs/edit_farmers_market.html.erb
<h2>Edit Pick-up Report</h2>
<%= render partial: "form_farmers_market" %>

app/views/logs/index.html.erb
<h2><%= @header %></h2>

<div class="row">
  <% if current_volunteer.any_admin? %>
    <div class="col-sm-6 text-left">
      <%= form_tag("/logs/new", method: "get", class: "form-inline") do %>
        <%= label_tag :region_id, 'New Log For:' %>
        <%= select_tag(:region_id, options_for_select(@my_admin_regions.collect{ |r| [r.name, r.id] }), { class: 'form-control' } ) %>
        <%= submit_tag("Go") %>
      <% end %>
    </div>
    <div class="col-sm-6">
      <%= form_tag("/logs/by_day", method: "get", class: "form-inline") do %>
        Jump to <%= date_select("date", :d, {order: [:day, :month, :year], start_year: 1920, end_year: DateTime.now.year}, { class: 'form-control' }) %>
        <%= submit_tag("Go") %>
      <% end %>
    </div>
  <% end %>
  <br />
  <br />
</div>

<div class="row">
  <div class="col-sm-12">
    <% if current_volunteer.assignments.length == 0 %>
      <p>You haven't been assigned to any regions, so you can't see anything yet. Ask a coordinator for your region to assign you!</p>
    <% elsif @shifts.length == 0 %>
      <p>No shifts found.</p>
    <% else %>
      <table class="table" id="data_table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Info</th>
            <th>When</th>
            <th>Volunteers</th>
            <th>Donor</th>
            <th>Recipient(s)</th>

            <% unless current_page?(controller: "logs", action: "open") %>
              <th>Weight</th>
              <th>Transport Type</th>
              <th>Food Type</th>
            <% end %>

            <th>Notes</th>

            <% if current_volunteer.any_admin? %>
              <th>Shift Logs Admin</th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%
            @shifts.each do |shift|
              row_bgcolor =
                if shift.volunteers_needed? && !current_page?(controller: "logs", action: "open")
                 'pink'
                elsif shift.volunteers_need_training?
                  'lightgreen'
                else
                  'white'
              end
          %>
            <tr style="background: <%= row_bgcolor %>;">
              <td>
                <%= shift.when.strftime("%Y-%m-%d") %>
              </td>
              <td>
                <% if shift.schedule_chain.present? %>
                  <%= link_to schedule_chain_path(shift.schedule_chain.id), class: 'btn btn-info info' do %>
                    <i class="fa fa-info-circle"></i>
                    Info
                  <% end %>
                <% else %>
                  One-time Shift
                <% end %>
              </td>
              <td>
                <%= readable_time_until(shift.first_log) %>
              </td>
              <td>
                <% if shift.volunteers_needed? %>
                  <%= link_to take_log_path(shift.first_log, ids: shift.log_ids), class: 'btn btn-primary take' do %>
                    <i class="fa fa-hand-rock-o"></i>
                    Cover Shift
                  <% end %>
                <% else %>
                  <% shift.volunteers.each do |volunteer| %>
                    <%= link_to volunteer.name, volunteer %><br />
                  <% end %>
                  <%= render 'take_or_leave', logs: shift.logs %>
                <% end %>

                <% unless shift.absences.empty? %>
                  <small>
                    <br />
                    (normally:
                      <% shift.absences.each do |absence| %>
                        <% absence.volunteer.present? ? absence.volunteer.name : 'Volunteer Deleted' %>,
                      <% end %>
                    )
                  </small>
                <% end %>
              </td>

              <td>
                <% shift.donors.each do |donor| %>
                  <%= link_to donor.name, donor %><br />
                <% end %>
              </td>

              <td>
                <% shift.recipients.each do |recip| %>
                  <%= link_to recip.name, recip %><br />
                <% end %>
              </td>

              <% unless current_page?(controller: 'logs', action: 'open') %>
                <td>
                  <%= shift.complete? ? shift.summed_weight.round : "?" %> lbs.
                </td>
                <td>
                  <% shift.transport_types.each do |transport_type| %> <%= transport_type.name %><br />
                  <% end %>
                </td>
                <td>
                  <% shift.food_types_by_log.each do |types| %>
                    <div><%= types.map(&:name).join(", ") %></div>
                  <% end %>
                </td>
              <% end %>

              <td style="font-size: 10pt;">
                <% shift.logs.each do |shift| %>
                  <%= word_wrap(shift.notes, line_width: 20).gsub("\n","<br />").html_safe unless shift.notes.nil? %>
                  <hr />
                <% end %>
              </td>
              <% if current_volunteer.any_admin?(shift.region) %>
                <td>
                  <% shift.logs.each do |log| %>
                    <%= link_to "edit log #{log.id}", edit_log_path(log), class: 'btn btn-primary' %><br />
                   <%= link_to "delete log #{log.id}", log, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete this shift's log?" }, method: :delete %><br />
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/logs/new.html.erb
<h2>New Pick-Up Report - Standard form</h2>
<%= render :partial => "form" %>

app/views/logs/new_farmers_market.html.erb
<h2>New Pick-up Report for Farmer's Market</h2>
<%= render partial: "form_farmers_market" %>

app/views/logs/select_location.html.erb
<%= form_tag("/logs/new", method: "get") do %>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= label_tag(:donor_id, 'Select Farmer\'s Market') %>
      <%= select_tag :donor_id, options_for_select((@locations).collect {|d| [d.name, d.id]}), {class: 'form-control select2'} %>
      <%= hidden_field_tag :region_id, @region.id %>
      <%= hidden_field_tag 'is_farmer_market', 1 %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= submit_tag "Use this location" %>
    </div>
  </div>
<% end %>

app/views/logs/show.html.erb
<h3>Log #<%= @log.id %></h3>
<table style="border-spacing: 1em;border-collapse: separate;">
  <tr>
    <th> Date </th>
    <td> <%= @log.when.strftime("%Y-%m-%d") %></td>
  </tr>
  <tr>
    <th>Info</th>
    <td>
      <% unless @log.schedule_chain.nil? %>
        <button class="btn btn-info info" onclick="window.location='/schedule_chains/<%= @log.schedule_chain.id %>';">
          <i class="fa fa-info-circle"></i>
          Info
        </button>
      <% else %>
        One-time Shift
      <% end %>
    </td>
  <tr>
    <th> When </th>
    <td> <%= readable_time_until @log %> </td>
  </tr>
  <tr>
    <th> Volunteers </th>
    <td>
      <% if @log.volunteers.empty? %>
        <button class="btn btn-primary take" onclick="window.location='<%= take_log_path(@log) %>';">
          <i class="fa fa-hand-rock-o"></i>
          Take
        </button>
      <% else %>
        <% @log.volunteers.each do |volunteer| %>
          <%= link_to volunteer.name, volunteer %><br />
        <% end %>
        <%= render 'take_or_leave', :logs=>[@log] %>
      <% end %>
      <% unless @log.absences.empty? %>
        <small><br>(normally <% @log.absences.each{ |a| %><%= a.volunteer.name %><% } %>)</small>
      <% end %>
    </td>
  </tr>
  <tr>
    <th> Donor </th>
    <td><% link_to @log.donor.name, @log.donor %></td>
  </tr>
  <tr>
    <th> Recipient(s) </th>
    <td> <% @log.recipients.each do |recip| %> <%= link_to recip.name, recip %> <br> <% end %></td>
  </tr>
  <tr>
    <th> Notes </th>
    <td><%= @log.notes.nil? ? "" : word_wrap(@log.notes,:line_width => 20).gsub("\n","<br>").html_safe %></td>
  </tr>
</table>