config/routes.rb
# frozen_string_literal: true


Webapp::Application.routes.draw do
  resources :assignments, only: [] do
    collection do
      get :knight
    end
  end

  resources :regions, except: [:show]

  resources :cell_carriers do as_routes end
  resources :transport_types do as_routes end

  resources :scale_types

  resources :absences do
    collection do
      get :all
    end
  end

  resources :logs do
    collection do
      get :by_day
      get :tardy
      get :last_ten
      get :open
      get :todo
      get :mine_past
      get :mine_upcoming
      get :being_covered
      get :new_absence
      get :create_absence
      get :receipt
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :stats_service
      get :stats
      get :export
    end
    member do
      get :take
      get :leave
    end
  end

  resources :schedule_chains do
    collection do
      get :today
      get :tomorrow
      get :yesterday
      get :open
      get :open_old
      get :mine
      get :mine_old
      get :take
      get :leave
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end
  end

  resources :locations do
    collection do
      get :recipients
      get :hubs
      get :sellers
      get :buyers
      get :index
      get :edit
      get :update
      get :create
      get :destroy
    end

    member do
      get :hud
    end
  end

  devise_for :volunteers, controllers: { sessions: 'sessions' }

  resources :volunteers do
    collection do
      get :home
      get :unassigned
      get :shiftless
      get :shiftless_old
      get :active
      get :inactive
      get :need_training
      get :super_admin
      get :region_admin
      get :stats
      get :shift_stats
      get :switch_user
      get :knight
      get :index
      get :edit
      get :update
      get :create
      get :destroy
      get :assign
    end
    member do
      get :reactivate
    end
  end

  resource :waiver, only: [:new, :create]

  namespace :region_admin do
    resources :donors, only: [:index]

    resources :food_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  devise_scope :volunteer do
    authenticated do
      root to: 'volunteers#home'
    end

    unauthenticated do
      root to: 'sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/log.rb
# frozen_string_literal: true

class Log < ActiveRecord::Base
  WHY_ZER0 = { 1 => 'No Food', 2 => "Didn't Happen" }

  belongs_to :schedule_chain
  belongs_to :donor, class_name: 'Location', foreign_key: 'donor_id'
  belongs_to :scale_type
  belongs_to :transport_type
  belongs_to :region

  has_many :log_volunteers
  has_many :volunteers, -> { where(log_volunteers: { active: true }) }, through: :log_volunteers
  has_many :inactive_volunteers, -> { where(log_volunteers: { active: false }) }, through: :log_volunteers
  has_many :log_recipients
  has_many :recipients, through: :log_recipients
  has_many :log_parts
  has_many :food_types, through: :log_parts

  has_and_belongs_to_many :absences

  scope :complete, -> { where(complete: true) }

  accepts_nested_attributes_for :log_recipients
  accepts_nested_attributes_for :log_volunteers
  accepts_nested_attributes_for :schedule_chain

  validates :notes, presence: { if: Proc.new{ |a| a.complete && a.summed_weight == 0 && a.summed_count == 0 && a.why_zero == 2 },
                                message: "can't be blank if weights/counts are all zero: let us know what happened!" }
  validates :transport_type_id, presence: { if: :complete }
  validates :donor_id, presence: { if: :complete }
  validates :scale_type_id, presence: { if: :complete }
  validates :when, presence: true
  validates :hours_spent, presence: { if: :complete }
  validates :why_zero, presence: { if: Proc.new{ |a| a.complete && a.summed_weight == 0 && a.summed_count == 0 } }

  attr_accessible :region_id, :donor_id, :why_zero,
                  :food_type_id, :transport_type_id, :flag_for_admin, :notes,
                  :num_reminders, :transport, :when, :scale_type_id, :hours_spent,
                  :log_volunteers_attributes, :weight_unit, :volunteers_attributes,
                  :schedule_chain_id, :recipients_attributes, :log_recipients_attributes, :log_volunteers_attributes,
                  :id, :created_at, :updated_at, :complete, :recipient_ids, :volunteer_ids, :num_volunteers

  # units conversion on scale type --- we always store in lbs in the database
  before_save { |record|
    return if record.region.nil?
    record.scale_type = record.region.scale_types.first if record.scale_type.nil? && record.region.scale_types.length == 1
    unless record.scale_type.nil?
      record.weight_unit = record.scale_type.weight_unit if record.weight_unit.nil?
      record.log_parts.each{ |lp|
        if record.weight_unit == 'kg'
          lp.weight = (lp.weight * (1.0/2.2).to_f).round(2) unless lp.weight.nil?
        elsif record.weight_unit == 'st'
          lp.weight = (lp.weight.to_f * (1.0/14.0).to_f).round(2) unless lp.weight.nil?
        end
        lp.save unless lp.new_record?
      }
      record.weight_unit = 'lb'
    end
  }

  def volunteers?
    self.volunteers.count > 0
  end

  def no_volunteers?
    self.volunteers.count == 0
  end

  def covering_volunteers
    self.log_volunteers
        .collect{ |lv| lv.covering ? lv.volunteer : nil }
        .compact
  end

  def covered?
    num_vols = num_volunteers || schedule_chain&.num_volunteers
    return volunteers.count >= num_vols if num_vols
    volunteers?
  end

  def volunteer?(volunteer)
    return false if volunteer.nil?
    volunteer_ids.include?(volunteer.id)
  end

  def summed_weight
    self.log_parts
        .collect{ |lp| lp.weight }
        .compact
        .sum
  end

  def summed_count
    self.log_parts
        .collect{ |lp| lp.count }
        .compact
        .sum
  end

  def prior_volunteers
    self.log_volunteers
        .collect{ |sv| (not sv.active) ? sv.volunteer : nil }
        .compact
  end

  #### CLASS METHODS

  def self.pickup_count(region_id)
    Log.where(region_id: region_id, complete: true).count
  end

  def self.picked_up_by(volunteer_id, complete=true, limit=nil)
    logs = joins(:log_volunteers)
    .where('log_volunteers.volunteer_id = ? AND logs.complete=? AND log_volunteers.active', volunteer_id, complete)
    .order('"logs"."when" DESC')
    .uniq

    if limit.present?
      logs.limit(limit.to_i)
    else
      logs
    end
  end

  def self.at(loc)
    if loc.donor?
      return Log.joins(:food_types)
                .select("sum(weight) as weight_sum, string_agg(food_types.name,', ') as food_types_combined, logs.id, logs.transport_type_id, logs.when")
                .where('donor_id = ?', loc.id)
                .group('logs.id, logs.transport_type_id, logs.when')
                .order('logs.when ASC')
    else
      return Log.joins(:food_types, :recipients)
                .select("sum(weight) as weight_sum, string_agg(food_types.name,', ') as food_types_combined, logs.id, logs.transport_type_id, logs.when, logs.donor_id")
                .where('recipient_id=?', loc.id)
                .group('logs.id, logs.transport_type_id, logs.when, logs.donor_id')
                .order('logs.when ASC')
    end
  end

  def self.picked_up_weight(region_id=nil, volunteer_id=nil)
    cq = 'logs.complete'
    vq = volunteer_id.nil? ? nil : "log_volunteers.volunteer_id=#{volunteer_id}"
    rq = region_id.nil? ? nil : "logs.region_id=#{region_id}"
    aq = 'log_volunteers.active'
    Log.joins(:log_volunteers, :log_parts)
       .where([cq, vq, rq, aq].compact.join(' AND '))
       .sum(:weight).to_f
  end

  def self.upcoming_for(volunteer_id)
    Log.joins(:log_volunteers)
       .where('active AND "when" >= ? AND volunteer_id = ?', Time.zone.today, volunteer_id)
       .order('logs.when')
  end

  def self.past_for(volunteer_id)
    Log.joins(:log_volunteers)
       .where('active AND "when" < ? AND volunteer_id = ?', Time.zone.today, volunteer_id)
       .order('logs.when')
  end

  def self.needing_coverage(region_id_list=nil, days_away=nil, limit=nil)
    if region_id_list
      if days_away
        Log.where('"when" >= ? AND "when" <= ?', Time.zone.today, Time.zone.today + days_away)
           .where(region_id: region_id_list)
           .order('logs.when')
           .limit(limit)
           .reject{ |log| log.covered? }
      else
        Log.where('"when" >= ?', Time.zone.today)
           .where(region_id: region_id_list)
           .order('logs.when')
           .limit(limit)
           .reject{ |log| log.covered? }
      end
    elsif days_away
      Log.where('"when" >= ? AND "when" <= ?', Time.zone.today, Time.zone.today + days_away)
         .order('logs.when')
         .limit(limit)
         .reject{ |log| log.covered? }
    else
      Log.where('"when" >= ?', Time.zone.today)
         .order('logs.when')
         .limit(limit)
         .reject{ |log| log.covered? }
    end
  end

  def self.being_covered(region_id_list=nil)
    Log.where('"when" >= ?', Time.zone.today)
       .where(region_id: region_id_list)
       .order('logs.when')
       .reject{ |log| log.covering_volunteers.empty? }
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << ['id', 'date', 'item types', 'item weights', 'item descriptions', 'total weight', 'donor', 'recipients', 'volunteers', 'scale', 'transport', 'hours spent', 'reminders sent', 'volunteer notes']
      all.each do |log|
        lps = log.log_parts
        csv << [log.id, log.when, lps.collect{ |lp| lp.food_type.nil? ? 'Unknown' : lp.food_type.name }.join(':'),
                lps.collect{ |lp| lp.weight }.join(':'),
                lps.collect{ |lp| lp.description.nil? ? 'None' : lp.description }.join(':'),
                log.summed_weight, log.donor.nil? ? 'Unknown' : log.donor.name, log.recipients.collect{ |r| r.nil? ? 'Unknown' : r.name }.join(':'),
                log.volunteers.collect{ |r| r.nil? ? 'Unknown' : r.name }.join(':'), log.scale_type.nil? ? 'Unknown' : log.scale_type.name,
                log.transport_type.nil? ? 'Unknown' : log.transport_type.name, log.hours_spent, log.num_reminders, log.notes]
      end
    end
  end
end

app/models/schedule_chain.rb
# frozen_string_literal: true

class ScheduleChain < ActiveRecord::Base
  default_scope { where(active: true) }

  belongs_to :transport_type
  belongs_to :scale_type
  belongs_to :region

  has_many :schedule_volunteers
  has_many :volunteers, -> { where(schedule_volunteers: { active: true }) }, through: :schedule_volunteers

  has_many :schedules
  has_many :locations, through: :schedules

  has_many :logs

  attr_accessible :region_id, :irregular, :backup, :transport_type_id,
                  :day_of_week, :detailed_start_time, :detailed_stop_time,
                  :detailed_date, :frequency, :temporary, :difficulty_rating,
                  :expected_weight, :hilliness, :schedule_volunteers,
                  :schedule_volunteers_attributes, :scale_type_ids,
                  :schedule_ids, :admin_notes, :public_notes, :schedules,
                  :schedule, :schedule_volunteers, :schedules_attributes,
                  :num_volunteers, :active

  accepts_nested_attributes_for :schedule_volunteers
  accepts_nested_attributes_for :schedules

  HILLINESS_OPTIONS = [
    'Flat',
    'Mostly Flat',
    'Some Small Hills',
    'Hilly for Reals',
    'Mountaineering'
  ].freeze

  DIFFICULTY_OPTIONS = [
    'Easiest',
    'Typical',
    'Challenging',
    'Most Difficult'
  ].freeze

  after_save do |record|
    record.schedule_volunteers.each do |sv|
      sv.destroy if sv.volunteer_id.blank?
    end
  end

  def covered?
    volunteers.count >= num_volunteers
  end

  # does the schedule chain start with a pickup and end with a dropoff?
  def functional?
    schedules.any? &&
      schedules.first.pickup_stop? &&
      schedules.last.drop_stop?
  end

  def mappable?
    return false unless functional?
    true
    # schedules.all? { |s| s.location&.address.present? }
  end

  # list all the schedules that don't have enough active volunteers
  # clarification: (in my regions) and (temporary or (no volunteers and last stop is dropoff))
  def self.open_in_regions(region_id_list)
    schedules = ScheduleChain.where(irregular: false).where(region_id: region_id_list) unless region_id_list.empty?
    return [] if schedules.nil?
    schedules.keep_if do |schedule|
      if schedule.functional?
        schedule.temporary || !schedule.covered?
      else
        false
      end
    end
    schedules
  end

  def self.for_location(loc)
    if loc.donor?
      ScheduleChain.for_donor(loc)
    else
      ScheduleChain.for_recipient(loc)
    end
  end

  def self.for_donor(d)
    Schedule.joins(:location).where('locations.location_type = ? AND locations.id = ?', Location::LOCATION_TYPES.invert['Donor'], d.id).collect(&:schedule_chain).uniq
  end

  def self.for_recipient(r)
    Schedule.joins(:location).where('NOT locations.location_type = ? AND locations.id = ?', Location::LOCATION_TYPES.invert['Recipient'], r.id).collect(&:schedule_chain).uniq
  end

  def food_types
    schedules.collect(&:food_types).flatten.uniq
  end

  def volunteers?
    volunteers.count.positive?
  end

  def no_volunteers?
    volunteers.count.zero?
  end

  def volunteers_needing_training?
    somebody_needs_training = false
    volunteers.each { |volunteer| somebody_needs_training |= volunteer.needs_training? }
    somebody_needs_training
  end

  def prior_volunteers
    schedule_volunteers.collect { |sv| !sv.active ? sv.volunteer : nil }.compact
  end

  def volunteer?(volunteer)
    return false if volunteer.nil?
    volunteers.collect(&:id).include?(volunteer.id)
  end

  def one_time?
    frequency == 'one-time'
  end

  def weekly?
    frequency == 'weekly'
  end

  def max_weight
    logs.collect(&:summed_weight).compact.max
  end

  def mean_weight
    ls = logs.collect(&:summed_weight)
    ls.empty? ? nil : ls.sum / ls.length
  end

  def next_pickup_time
    return nil unless weekly? && !irregular

    next_pickup = Time.zone.today
    next_pickup += 1 if day_of_week == next_pickup.wday &&
                        detailed_start_time.strftime('%H%m').to_i < Time.zone.now.strftime('%H%m').to_i

    while next_pickup.wday != day_of_week
      next_pickup += 1
    end

    {
      start: Time.new(
        next_pickup.year,
        next_pickup.month,
        next_pickup.day,
        detailed_start_time.hour,
        detailed_start_time.min
      ),
      stop: Time.new(
        next_pickup.year,
        next_pickup.month,
        next_pickup.day,
        detailed_stop_time.hour,
        detailed_stop_time.min
      )
    }
  end

  def donor_stops
    schedules.select(&:pickup_stop?)
  end

  def recipient_stops
    schedules.select(&:drop_stop?)
  end

  def donors
    donor_stops.collect(&:location)
  end

  def recipients
    recipient_stops.collect(&:location)
  end

  def from_to_name
    "#{schedules.first.location.try(:name)} to #{schedules.last.location.try(:name)}"
  end

  def related_shifts
    location_ids = donors.collect { |donor|
      donor.location_type == Location::LOCATION_TYPES.invert['Hub'] ? nil : donor.id
    }.compact

    return [] if location_ids.empty?

    Schedule.where('schedule_chain_id != ?', id).where(location_id: location_ids).reject do |x|
      x.schedule_chain.nil?
    end
  end
end

app/views/schedule_chains/edit.html.erb
<h2>Edit Schedule Item</h2>
<%= render partial: "form" %>

app/views/schedule_chains/index.html.erb
<h2><%=@page_title%></h2>

<div class="row">
  <% if current_volunteer.any_admin? && !@my_admin_regions.nil? %>
    <div class="col-sm-6 text-left">
      <%= form_tag("/schedule_chains/new", method: "get", class: 'form-inline') do %>
        New Scheduled Route For <%= select_tag("region_id", options_for_select(@my_admin_regions.collect{ |r| [r.name,r.id] }), {class: 'form-control'}) %>
        <%= submit_tag("Go") %>
      <% end %>
    </div>
  <% end %>
</div>

<% if current_volunteer.assignments.length == 0 %>
  <p>You haven't been assigned to any regions, so you can't see anything yet. Ask a coordinator for your region to assign you!</p>
<% elsif @chains.length == 0 %>
  <p>Local schedule list is empty.</p>
<% elsif current_volunteer.regions.length == 0 %>
  <p>You aren't assigned to any regions, so you can't see anything yet. Ask a coordinator in your region to assign you!</p>
<% else %>

  <div id="modal"></div>

  <table class="table" id="data_table">
    <thead>
      <tr>
        <th>Info</th>
        <th>Day</th>
        <th>Stops</th>
        <th>Volunteers</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Notes</th>
        <% if current_volunteer.any_admin? %>
          <th> Admin Notes</th>
        <% end %>
        <th>Prior Volunteers</th>
        <th>Transport</th>
        <th>Food Types</th>
        <% if current_volunteer.any_admin? %>
          <th>Link</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%
        @chains.each do |schedule|
          row_bgcolor = nil
          if schedule.no_volunteers?
            row_bgcolor = "pink"
          elsif schedule.temporary
            row_bgcolor = "#9999FF"
          elsif schedule.volunteers_needing_training?
            row_bgcolor = "lightgreen"
          elsif not schedule.functional?
            row_bgcolor = "yellow"
          end
      %>
        <tr style="<%= "background-color: #{row_bgcolor};" if row_bgcolor.present? %>">
          <td>
            <a class="btn btn-info info" href="/schedule_chains/<%= schedule.id %>">
              <i class="fa fa-info-circle"></i>
              Info
            </a>
          </td>
          <td>
            <strong>
              <% if schedule.one_time? %>
                <%= schedule.detailed_date %>
              <% else %>
                <span style="display:none;">
                  <%= schedule.day_of_week %>
                </span>
                <%= schedule.day_of_week.nil? ? "" : Date::DAYNAMES[schedule.day_of_week] %>
              <% end %>
            </strong>
          </td>
          <td>
            <% unless schedule.schedules.nil? %>
              <% schedule.schedules.each do |stop| %>
                <% next if stop.location.nil? %>
    						<%= link_to stop.location.name, stop.location %>
        				<% if stop.location.donor? %>
              		(Donor)
    						<% else %>
    							(Recipient)
    						<% end %>
                <br />
    					<% end %>
            <% end %>
          </td>
          <td>
            <% if schedule.no_volunteers? or schedule.temporary %>
              <a class="btn btn-primary take" href="/schedule_chains/take?id=<%= schedule.id %>">
                <i class="fa fa-hand-rock-o"></i>
                Take Weekly Shift
              </a>
            <% else %>
              <% schedule.volunteers.each do |volunteer| %>
                <%= link_to volunteer.name, volunteer %><br />
              <% end %>
              <%= render 'take_or_leave', schedule: schedule %>
            <% end %>
          </td>
          <td>
            <%= readable_start_time schedule %>
          </td>
          <td>
            <%= readable_stop_time schedule %>
          </td>
          <td style="font-size: 10pt;">
            <%= word_wrap(schedule.public_notes, line_width: 20).gsub("\n","<br>").html_safe unless schedule.public_notes.nil? %>
          </td>
          <% if current_volunteer.any_admin? %>
            <td>
              <%= word_wrap(schedule.admin_notes,:line_width => 20).gsub("\n","<br>").html_safe unless schedule.admin_notes.nil? or !current_volunteer.region_admin?(schedule.region) %>
            </td>
          <% end %>
          <td style="font-size: 10pt;">
            <% schedule.prior_volunteers.each do |prior_volunteer| %>
              <%= link_to prior_volunteer.name, prior_volunteer %><br />
            <% end %>
          </td>
          <td><%= schedule.transport_type.nil? ? "?" : schedule.transport_type.name %></td>
          <td>
            <% foods = ""
                schedule.schedules.each do |stops|
                  if stops.pickup_stop?
                    foods += "<li><em>" + (stops.location.name + ":</em> " + stops.food_types.collect{ |ft| ft.name }.join(", ") + "\n")
                  end
    		      end %>
            <ul>
              <%= foods.html_safe %>
            </ul>
          </td>
          <td>
            <% if current_volunteer.any_admin? %>
              <%= link_to 'edit', edit_schedule_chain_path(schedule) %><br>
              <%= link_to "delete", schedule, data: { confirm: "Are you sure?" }, method: :delete %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<br><br>
<b>Key:</b>
<span class="label" style="background: yellow">Missing Donor/Recipient</span>
<span class="label" style="background: pink">No Volunteer</span>
<span class="label" style="background: lightgreen">Needs Training</span>
<span class="label" style="background: #9999FF">Temporary Cover</span>

app/views/schedule_chains/show.html.erb
<div class="row">

  <div class="col-sm-6">

    <h2>
      <i class='fa fa-location-arrow'></i>
      <%= if @chain.functional?
              if @chain.recipient_stops.length == 1
			    "Delivery to " + @chain.schedules.last.location.name
              else
                routename = "Deliveries to "
                @chain.recipient_stops.each do |stop|
 		              next if stop.location.nil?
                  routename += stop.location.name
                  if stop != @chain.recipient_stops.last
                    routename += ", "
                  end
                end
                routename
              end
		    else
			    "Underspecified Schedule"
		    end%></h2>

    <% unless @chain.next_pickup_time.nil? || !@chain.functional? %>
      <div class="pull-right">
        <a href="http://www.google.com/calendar/event?action=TEMPLATE&text=
            <%=u "Food Rescue: #{(@chain.schedules.empty? || @chain.schedules.first.location.nil?) ? "Unknown" : @chain.schedules.first.location.name} -> #{(@chain.schedules.empty? || @chain.schedules.last.location.nil?) ? "Unknown" : @chain.schedules.last.location.name}" %>
            &dates=<%=u @chain.next_pickup_time[:start].gmtime.strftime("%Y%m%dT%H%M%SZ") %>/<%=u @chain.next_pickup_time[:stop].gmtime.strftime("%Y%m%dT%H%M%SZ") %>&details=<%=u @chain.public_notes%>&location=<%=u @chain.schedules.first.location.address%>&trp=true&sprop=http%3A%2F%2Fboulderfoodrescue.org&sprop=name:Boulder%20Food%20Rescue" target="_blank"><img src="//www.google.com/calendar/images/ext/gc_button6.gif" border=0></a>
      </div>
    <% end %>

    <p>
      <%= readable_pickup_timespan @chain %>
      <% unless @chain.next_pickup_time.nil? %>
        (next pickup <%= @chain.next_pickup_time[:start].to_s(:long_ordinal) %>)
      <% end %>
      .
    </p>

    <% unless @chain.public_notes.nil? || @chain.public_notes.strip == "" %>
      <p><b>Notes:</b> <%= word_wrap(@chain.public_notes,:line_width => 80).gsub("\n","<br>").html_safe %></p>
    <% end %>

    <% unless @chain.expected_weight.nil? || @chain.max_weight.nil? || @chain.mean_weight.nil? %>
      <p><b>Expected Weight:</b> <%= @chain.expected_weight %> <em>(current mean = <%= @chain.mean_weight.round %>, max = <%= @chain.max_weight.round %>)</em></p>
    <% end %>

    <% unless @chain.hilliness.nil? %>
      <p><b>Hilliness:</b> <%= ScheduleChain::HILLINESS_OPTIONS[@chain.hilliness] %></p>
    <% end %>

    <% unless @chain.difficulty_rating.nil? %>
      <p><b>Overall Difficulty:</b> <%= ScheduleChain::DIFFICULTY_OPTIONS[@chain.difficulty_rating] %></p>
    <% end %>

    <h3>
      <i class="fa fa-users"></i>
      Current Volunteers
    </h3>
    <p>
      <% if @chain.volunteers.count == 0 %>
        No volunteers yet...
        <%= link_to take_schedule_chains_path(id: @chain), data: { confirm: "Are you sure you want to sign up for this weekly pickup?" }, class: 'btn btn-primary' do %>
          <i class="fa fa-hand-rock-o"></i>
          <strong>Signup for this <u>weekly</u> pickup now!</strong>
        <% end %>

      <% else %>
        <ul>
          <% @chain.volunteers.each do |volunteer| %>
            <li><%= link_to volunteer.name, "mailto:#{volunteer.email}" %><%= volunteer.phone.nil? ? "" : ": #{volunteer.phone}" %></li>
          <% end %>
        </ul>
      <% end %>
    </p>

    <% unless @sorted_related_shifts.empty? %>
      <h3>Other Shifts at this Donor</h3>
      <ul>
        <% @sorted_related_shifts.each{ |shift|
          next if(shift.schedule_chain.nil? || shift.schedule_chain.volunteers.empty?)
        %>
          <li>
            <% if shift.schedule_chain.day_of_week.present? %>
              <p>
                <strong>
                  <%= Date::DAYNAMES[shift.schedule_chain.day_of_week] %>
                </strong>
              </p>
            <% else %>
              <p>
                <strong>Unknown/Varies.</strong>
              </p>
              <p>Day of Week is empty for Shift <%= shift.id %> for <%= link_to "schedule chain #{shift.schedule_chain.id}", edit_schedule_chain_path('schedule chain') %>, this may be incorrect. Email volunteer or your region admin if you're concerned.</p>
            <% end %>
            <ul>
              <% shift.schedule_chain.volunteers.each do |volunteer| %>
                <li><%= link_to volunteer.name, "mailto:#{volunteer.email}" %><%= volunteer.phone.nil? ? "" : ": #{volunteer.phone}" %></li>
              <% end %>
            </ul>
          </li>
        <% } %>
      </ul>
    <% end %>
  </div>

  <div class="col-sm-6">
    <% if @chain.mappable? %>
      <h2>
        <i class='fa fa-bicycle'></i>
        Bicycling Directions
      </h2><br/>
      <iframe width="600" height="450"frameborder="0" style="border: 0;" src=<%= @embed_request_url %>></iframe>
      <div><em>NOTE: This may not include ALL stops if a stop has an invalid address.</em></div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <% if @chain.functional? %>
      <h3>Stops:</h3>
      <p>
  	  <% @chain.schedules.each do |stop|
        next if stop.nil? || stop.location.nil? %>

        <div class="col-sm-6">
          <div class="well">
            <h4>
              <i class='fa fa-building'></i>
              <%= stop.location.name %> <%= stop.pickup_stop? ? " (Donor)" : "(Recipient)" %>
            </h4>
            <blockquote>
              <i class='fa fa-map-marker'></i>
              <%= stop.location.address %>
            </blockquote>

            <% unless stop.location.entry_info.blank? %>
                <p><strong>Entry:</strong> <%= stop.location.entry_info.gsub("\n","<br />").html_safe %></p>
            <% end %>

            <% unless stop.location.equipment_storage_info.blank? %>
                <p><strong>Equipment:</strong> <%= stop.location.equipment_storage_info.gsub("\n","<br>").html_safe %></p>
            <% end %>

            <% unless stop.location.food_storage_info.blank? %>
                <p><strong>Food:</strong> <%= stop.location.food_storage_info.gsub("\n","<br>").html_safe %></p>
            <% end %>

            <% unless stop.location.onsite_contact_info.blank? %>
                <p><strong>Contact:</strong> <%= stop.location.onsite_contact_info.gsub("\n","<br>").html_safe %></p>
            <% end %>

            <% unless stop.location.exit_info.blank? %>
                <p><strong>Exit:</strong> <%= stop.location.exit_info.gsub("\n","<br>").html_safe %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>